# -*- coding: utf-8 -*-
"""`slides.yaml` -> `talk.tex` (Beamer + metropolis).

    python scripts/build_deck.py slides.yaml -o out/talk.tex
    cd out && pdflatex talk.tex && pdflatex talk.tex     # twice: page numbers, progress bar

Why Beamer
  If the paper is LaTeX, this uses the same engine, the same figure files,
  the same symbols. With no conversion step, a transcription accident in a
  figure, a formula, or a minus sign structurally cannot happen. The output
  is a single PDF, so it comes out identical even when the venue PC has no
  matching font.

Traps built in here (every one of these actually happened)
  - `\\begin{frame}[standout]` gets its next line eaten as the frametitle if
    that line starts with `{` -> put `\\vspace{0pt}` before the first line.
  - Without `block=fill` the block has no background, and under `block=fill`
    a block with no title becomes an empty gray band -> a block always gets
    a title.
  - pdflatex + cmss is a bitmap font, so there is no 40pt: the minus sign
    next to a big number stretches out like an em dash -> `lmodern` +
    `\\bigminus` (a hand-drawn bar).
  - A figure that gets cropped needs both `max width` and `max height` given
    together. Giving only one lets it overflow.
"""
import argparse
import io
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import deckspec
import design
from deckspec import load, spit, render_markup  # noqa: E402

# The typesetting engine. Chosen with `meta.engine`. Default is `pdflatex`.
#
#   Before this existed, the preamble was a module constant with
#   `\usepackage[T1]{fontenc}` hard-coded in. So building a deck from a
#   non-Latin-script manuscript would not compile, and the advice the builder
#   left was "use XeLaTeX," except there was no way to do that. The only
#   path left was hand-editing the generated `.tex`, exactly what this skill
#   forbids in section 1. Advice with no way to act on it is not advice, it
#   is a dead end.
#
#   Choosing `xelatex` sets up `fontspec` and a CJK font. `meta.cjk_font`
#   changes the font name (default Malgun Gothic, Windows's default Hangul font).
ENGINES = {
    "pdflatex": (r"""\usepackage{lmodern}      %% cmss is a bitmap font, so the minus sign gets mangled at large sizes
\usepackage[T1]{fontenc}  %% without it, OT1 prints `<` as an inverted exclamation mark and `>` as an inverted question mark"""),
    "xelatex": (r"""%% XeLaTeX typesets non-ASCII (Hangul, kana, Han characters) directly.
%%   `fontenc` and `lmodern` are not used (they are for an 8-bit engine and would hurt here).
%% It's `kotex`, not `xeCJK`. Following Chinese/Japanese convention, xeCJK eats
%%   the space between characters, but Korean uses spacing between words.
%%   Typesetting it for real, xeCJK ran a Korean sentence together into one
%%   unspaced word ("무엇을구축했나"), and `CJKspace=true` did not fix it
%%   either. kotex keeps the spacing as-is.
\usepackage{fontspec}
\usepackage{kotex}
\setmainhangulfont{%(cjkfont)s}
\setsanshangulfont{%(cjkfont)s}
\setmonohangulfont{%(cjkfont)s}"""),
}

PREAMBLE = r"""%% This file is generated by build_deck.py. Do not edit it by hand;
%% to change it, edit slides.yaml and regenerate, or it drifts apart from the PPTX and the script.
\documentclass[aspectratio=%(ratio)s,%(basept)spt]{beamer}
\usetheme[block=fill,numbering=fraction,progressbar=frametitle]{metropolis}
%(fonts)s
\usepackage{booktabs}
\usepackage{array}       %% the m{} column type: an image grid's fixed width, vertically centered
\usepackage{amssymb}     %% symbols like \lesssim, \gtrsim, \top; `deckspec.MATH_SYM` routes these here
\usepackage[export]{adjustbox}
\newsavebox{\ptTbl}     %% measure the table once to see if it shrinks; if it does, drop the text below it one size too
\usepackage{graphicx}
\usepackage{tikz}       %% `figure.highlight`: a look-here outline over a pasted figure
\graphicspath{{%(figdir)s}}

%% Semantic color is the mechanism that makes "scan by color, don't read the
%%   table" possible. Red is the bad side (a judged regression), green is the
%%   good side (an effect/recommendation). An unjudged cell gets no mark.
%% All three colors clear WCAG AA (4.5:1) on both a white background and the
%%   block background. Measured, the original palette failed all three, and
%%   mHi was 1.79:1 on the block, effectively unreadable. The hues stay the
%%   same; only the brightness was lowered to pass.
\definecolor{mHi}{HTML}{%(c_hi)s}
\definecolor{mHit}{HTML}{%(c_hit)s}
\definecolor{mSafe}{HTML}{%(c_safe)s}
%% The two colors above are unreadable on a dark background (standout). Separate bright variants are used there.
\definecolor{mHitLt}{HTML}{%(c_hit_lt)s}
\definecolor{mSafeLt}{HTML}{%(c_safe_lt)s}
%% Block background: metropolis's default (#CED2D3) is too dark, and every
%%   semantic color on top of it falls below 4.5:1. Unified with the bright
%%   value the PPTX builder was already using, since the two artifacts had
%%   already diverged right here.
%% A page number's denominator must be the main deck's slide count.
%%   metropolis's default `\inserttotalframenumber` also counts the backup
%%   slides after `\appendix`, so a 2-slide main deck prints as `1/4`.
%%   `\insertmainframenumber` counts only the main deck. With no backup
%%   slides the two are equal, so it is safe to use either way.
\setbeamertemplate{frame numbering}{\insertframenumber/\insertmainframenumber}
\definecolor{blockBG}{HTML}{%(c_block)s}
\setbeamercolor{block body}{bg=blockBG}
\setbeamercolor{block body alerted}{bg=blockBG}
\setbeamercolor{block body example}{bg=blockBG}
%% The title band has to change to match. Changing only the body leaves the
%%   title on the old background, and metropolis's accent color (#EB811B)
%%   comes out at 1.8:1 on it, nearly unreadable.
\setbeamercolor{block title}{bg=blockBG,fg=mDarkTeal}
\setbeamercolor{block title alerted}{bg=blockBG,fg=mHit}
\setbeamercolor{block title example}{bg=blockBG,fg=mSafe}

%% A minus sign at the 40pt size stretches out like an em dash from font substitution, so it is drawn by hand instead.
\newcommand{\bigminus}{\raisebox{0.27em}{\rule{0.33em}{0.115em}}\kern0.05em}

\title{%(title)s}
%(subtitle)s
%(author)s
%(institute)s
%(venue)s

\begin{document}

\maketitle
"""


# pdflatex cannot use non-ASCII characters. Only what actually shows up in
#   a talk's manuscript is mapped here. Without this, a single character like
#   `ΔT` kills the compile, and the only way to find out is reading a 45KB log.
SYMBOL = {
    "Δ": r"$\Delta$", "μ": r"$\mu$", "σ": r"$\sigma$",
    "×": r"$\times$", "±": r"$\pm$", "≤": r"$\leq$",
    "≥": r"$\geq$", "≈": r"$\approx$", "→": r"$\rightarrow$",
    "−": "-", "–": "--", "—": "---",
    "‘": "`", "’": "'", "“": "``", "”": "''",
    " ": " ", "…": r"\ldots{}", "·": r"\textperiodcentered{}",
    "†": r"\textdagger{}", "‡": r"\textdaggerdbl{}", "★": r"$\star$",
    "≪": r"$\ll$", "≫": r"$\gg$",
}
# Greek letters and common math symbols come from the same table as deckspec:
#   pdflatex used to stop on β/Σ in the body text. Mapping them to `$\beta$`
#   typesets on both engines.
for _n, _c in list(deckspec.GREEK.items()) + list(deckspec.MATH_SYM.items()):
    if len(_c) == 1 and _c not in SYMBOL and _n not in ("sqrt", "|", "mid", "cdot"):
        SYMBOL[_c] = "$\\%s$" % _n
SYMBOL.setdefault("√", r"$\surd$")
# A Latin accented letter (é, è, ü, ñ) is typeset directly by pdflatex under
#   T1/utf8, so it is not warned about: "Candès" printed fine but still
#   triggered an "unusable character" warning.
LATIN_OK = set(chr(c) for c in range(0xC0, 0x180)) - {"×", "÷"}
# A run of super/subscript characters becomes one formula. Breaking it
#   character by character into `$^{-}$$^{4}$` leaves gaps between them.
_SUP_BACK = {v: k for k, v in deckspec._SUP.items()}
_SUB_BACK = {v: k for k, v in deckspec._SUB.items()}
_SUP_RUN = re.compile("[%s]+" % "".join(_SUP_BACK))
_SUB_RUN = re.compile("[%s]+" % "".join(_SUB_BACK))


def _scripts(s):
    s = _SUP_RUN.sub(lambda m: "$^{%s}$" % "".join(_SUP_BACK[c] for c in m.group(0)), s)
    return _SUB_RUN.sub(lambda m: "$_{%s}$" % "".join(_SUB_BACK[c] for c in m.group(0)), s)


def symbols(s, warn=None, where=""):
    """Non-ASCII into LaTeX. An unknown character is flagged, never passed
    through silently."""
    s = deckspec.accents_to_tex(s)
    s = _scripts(s)
    for a, b in SYMBOL.items():
        s = s.replace(a, b)
    if warn is not None:
        bad = sorted({c for c in s if ord(c) > 127 and c not in LATIN_OK})
        if bad:
            warn.append("pdflatex cannot use character(s) %s (%s). "
                        "Convert to ASCII, or set `meta.engine: xelatex`"
                        % (" ".join("%r U+%04X" % (c, ord(c)) for c in bad), where))
    return s


def esc(s):
    """Escape LaTeX special characters. A currency `$` becomes `\\$` (it is
    not math, see `deckspec.CURRENCY`)."""
    if s is None:
        return ""
    return _esc(deckspec.hold_currency(s)).replace(deckspec.CUR, "\\$")


def _esc(s):
    """Escape LaTeX special characters.

    If a backslash or `$` is already present, this is treated as the author
      having written LaTeX directly, and left alone. So it has to be called
      before `minus()`: reversing the order makes `esc` skip the whole string
      because of the backslash `minus()` already inserted, and a math-only
      character like `^` goes out raw, killing the compile with "Missing $
      inserted." This has happened many times in real papers.
    """
    if s is None:
        return ""
    s = str(s)
    # Judged from the characters as they came in. Checking after symbols are
    #   substituted sees the dollar sign in the `$\pm$` this code already
    #   inserted and concludes "the author wrote LaTeX," and then a raw `%`
    #   in that line comments out the rest of the line, even the frame's
    #   closing brace. The build has died this way. Any string with both a
    #   substituted symbol and a character that needs escaping was
    #   guaranteed to break here.
    # Turns `->` into an arrow first. `SYMBOL` already knows the -> arrow
    #   character, so this only needs to get it that far. The deck, PPTX,
    #   script, and figures all use the same character.
    s = deckspec.arrows(s)
    # An unpaired `$` is a literal dollar sign: "(in $)" stopped the build with "Missing $".
    if len(re.findall(r"(?<!\\)\$", s)) % 2:
        s = re.sub(r"(?<!\\)\$", "\\\\$", s)
    # A combining accent (m̂) goes to math first, since pdflatex stops on that character.
    s = deckspec.accents_to_tex(s)
    author_latex = "\\" in s or "$" in s

    def _sym(x):
        x = _scripts(x)
        for a, b in SYMBOL.items():  # symbol substitution also applies to the author's own LaTeX
            x = x.replace(a, b)
        return x
    if author_latex:
        s = _sym(s)
        # LaTeX the author wrote is left untouched, except for a bare `%`.
        #   In LaTeX, `%` always turns the rest of that line into a comment.
        #   There is no case of "I wanted a percent sign on screen, and I
        #   wanted it to become a comment." What cannot be intentional is
        #   safe to block.
        return re.sub(r"(?<!\\)%", r"\\%", s)
    for a, b in (("&", r"\&"), ("%", r"\%"), ("#", r"\#"), ("_", r"\_"),
                 ("{", r"\{"), ("}", r"\}"),
                 ("^", r"\textasciicircum{}"), ("~", r"\textasciitilde{}")):
        s = s.replace(a, b)
    # Escaping first, symbols after. Reversed, the braces in the `\ldots{}`
    #   this code already inserted get escaped into `\{\}`, printing "...{}" on
    #   screen.
    return _sym(s)


MATH = re.compile(r"\$[^$]*\$")
# If preceded by another hyphen, it is not a minus sign: the en dash in
#   "8–15" becomes `--`, and reading the second `-` as a minus would print "8-−15."
_MINUS = re.compile(r"(?<![\w.\-])[−-](?=\d)")


def minus(s):
    """A leading Unicode minus/hyphen into a LaTeX glyph. Only right before a digit.

    Leaves the inside of `$...$` untouched. The `-` in `$p<10^{-4}$` is
      already a math minus sign, and touching it here turns it into
      `$p<10^{\\textminus 4}$`: it still compiles, but only the exponent
      quietly prints wrong. The builder must not rewrite a formula the author
      wrote by hand.
    """
    s = str(s)
    out, i = [], 0
    for m in MATH.finditer(s):
        out.append(_MINUS.sub(r"\\textminus ", s[i:m.start()]))
        out.append(m.group(0))                     # pass a formula through untouched
        i = m.end()
    out.append(_MINUS.sub(r"\\textminus ", s[i:]))
    return "".join(out)




def _mark(color, rule=False):
    """Meaning is never carried by color alone.

    `<hit>` and `<safe>` are this deck's whole reading mechanism, but
    red (#C0392B) and green (#1E8449) become the same mustard shade to a
    red-green colorblind eye: the distance between them drops from 181 to
    41.5 (23%). A caption that says "red = regression" ends up pointing at a
    color that is not on the screen, and for about 8% of men the mechanism
    disappears entirely.

    So the loss side alone also gets an extra underline. The distinction
    survives even when the color does not: in black-and-white print, on a
    low-quality projector, in a photocopy. The author changes nothing; the
    spec already knows the meaning, and the builder draws one more channel.
    """
    # The underline appears only under the colorblind option (`meta.colorblind`). The default is color alone.
    def f(x):
        if rule and deckspec.SECOND_CHANNEL:
            return "\\textcolor{%s}{\\textbf{\\underline{%s}}}" % (color, x)
        return "\\textcolor{%s}{\\textbf{%s}}" % (color, x)
    return f


# Two sets: light background / dark background (standout)
# `c` (code) is pulled out separately by `fmt` before escaping. After
#   escaping, a curly quote turns into a backtick and looks like code. What
#   arrives here is only that kind of quote, so it is returned as-is.
MARKS = {"b": lambda x: "\\textbf{%s}" % x, "i": lambda x: "\\emph{%s}" % x,
         "hit": _mark("mHit", True), "safe": _mark("mSafe"),
         "hi": _mark("mHi"), "c": lambda x: "`%s`" % x}
MARKS_DARK = {"b": lambda x: "\\textbf{%s}" % x, "i": lambda x: "\\emph{%s}" % x,
              "hit": _mark("mHitLt", True), "safe": _mark("mSafeLt"),
              "hi": _mark("mHi"), "c": lambda x: "`%s`" % x}

_CODE_ESC = {"\\": "\\textbackslash{}", "{": "\\{", "}": "\\}", "$": "\\$",
             "&": "\\&", "%": "\\%", "#": "\\#", "_": "\\_",
             "^": "\\textasciicircum{}", "~": "\\textasciitilde{}"}


def _hold_code(s):
    """Pull `code` out into a placeholder marker: [(marker, \\texttt{...})]."""
    held = []

    def f(m):
        held.append("\\texttt{%s}" % "".join(_CODE_ESC.get(c, c) for c in m.group(1)))
        return u"\ue000%d\ue001" % (len(held) - 1)
    return deckspec.CODE.sub(f, str(s)), held


def _put_code(s, held):
    for i, t in enumerate(held):
        s = s.replace(u"\ue000%d\ue001" % i, t)
    return s


def fmt(s, dark=False):
    """One span of text going to the screen. Order is everything.

    (1) `esc` special-character escaping -> (2) inline markup -> (3) minus signs.
    Applying markup first makes `esc` skip the whole thing because of `\\textbf`'s backslash.
    `dark` is for standout: a dark red/green on a dark background is unreadable.
    """
    s, held = _hold_code("" if s is None else s)
    return _put_code(minus(render_markup(esc(s), MARKS_DARK if dark else MARKS)), held)


def frame_title(s):
    return "\\begin{frame}{%s}\n" % fmt(s["title"]) if s.get("title") else \
           "\\begin{frame}\n"


def formula_body(s):
    """One line of a defining formula, centered under the lead, large. Shows
    the formula without using an impact slide: planning.md's shapes section
    calls for "large," but the only large text is standout's big, which once
    turned a formula into five impact slides."""
    if not s.get("formula"):
        return []
    return ["  \\vspace{0.2em}%",
            "  {\\centering\\Large %s\\par}" % fmt(s["formula"]),
            "  \\vspace{0.3em}%"]


def lead_body(s):
    """A one-line lead-in.

    If the line right after `\\begin{frame}{title}` starts with `{`, beamer
      eats it as the frame subtitle. metropolis does not draw a subtitle, so
      that line vanishes entirely from the PDF, with zero LaTeX errors. This
      guard was already in place for `standout`, but missing here. With
      `\\vspace{0pt}%` in front, it no longer reads as a subtitle.
    """
    if not s.get("lead"):
        return []
    return ["  \\vspace{0pt}%",
            "  {\\small %s}\n" % fmt((s["lead"]))]


MAX_ROWS = 12          # measured: with the title band on a 16:9 slide, this is around where it overflows


def render_table(t, warn=None, where="", fit="\\textwidth", dark=False, main=True):
    # Moving a paper's table over whole overflows. A real paper's 19-row
    #   table came in as-is and ran off the slide. Trimming it is a human's
    #   job, but it has to be said out loud.
    if warn is not None and len(t["rows"]) > MAX_ROWS:
        warn.append("Table has %d rows (%s), which overflows the slide around %d rows. "
                    "Cut rows or split it into slides" % (len(t["rows"]), where, MAX_ROWS))
    # A large table in the main deck shrinks to scriptsize and becomes
    #   unreadable from the back row, as happened with a 10-row, 5-column
    #   leaderboard. If it is a leaderboard (rows = methods), draw the one
    #   metric that matters as dots (planning.md's leaderboard section), and
    #   keep the full table as a backup.
    _nc = max([len(r) for r in t["rows"]] + [len(t.get("header") or [])])
    if warn is not None and main and len(t["rows"]) >= 9 and _nc >= 5:
        warn.append("Main-deck table is %d rows x %d columns (%s), so text shrinks too small to read from "
                    "the back row. If it's a leaderboard (rows are methods), draw the one metric that "
                    "matters as `chart: {kind: dots}` and keep the full table as a backup (planning §leaderboard)"
                    % (len(t["rows"]), _nc, where))
    # Alignment is decided by the column's content: a number is right-aligned,
    #   text is left-aligned. Pinning the first column to l and the rest to r
    #   left a text column stuck to the right.
    align = t.get("align") or deckspec.column_align(t["rows"])
    # A `tabular` does not shrink to fit a column width. Dropping it straight
    #   into a two-column layout invades the neighboring column and overlaps
    #   text. `max width` only shrinks it when it overflows.
    # A table is tightened to `\scriptsize` to fit more into one screen.
    #   Leaving it to adjustbox's shrinking alone makes the text sizes uneven.
    # `size` is a meaning, not a LaTeX command name. Emitting `fine` as-is
    #   produced `{\\fine`, which stopped the compile.
    sz = {"small": "footnotesize", "fine": "scriptsize",
          "footnotesize": "footnotesize", "scriptsize": "scriptsize"}.get(
        str(t.get("size") or ""), None)
    # A table is boxed and measured first, then placed. When it is wider than
    #   the column and `max width` shrinks it, the body text can end up
    #   smaller than the note under the table (footnotesize), so the attached
    #   note printed larger than the body. The table's font size is recorded
    #   (`\ptTblPt`), and only when the actual size, that size times the
    #   shrink ratio, comes out smaller than footnotesize does the note under
    #   the table drop to scriptsize (the deck's floor). Doing "one step down
    #   whenever it shrinks" made a note under a table that shrank only 2%
    #   come out far smaller than the body. It never drops below the floor.
    out = ["  \\sbox{\\ptTbl}{%"]
    if sz:
        out.append("  {\\%s" % sz)
    out.append("  \\xdef\\ptTblPt{\\csname f@size\\endcsname}%")
    # A table inside an impact slide (dark background) draws no rules.
    #   booktabs's black rules are invisible on a dark background and look
    #   misaligned. The color also switches to the bright variant.
    rule = (lambda x: []) if dark else (lambda x: ["    \\%s" % x])
    out += ["  \\begin{tabular}{%s}" % align] + rule("toprule")
    if t.get("header"):
        out.append("    " + " & ".join(fmt(h, dark) for h in t["header"]) + r" \\")
        out += rule("midrule")
    for row in t["rows"]:
        # A row where only the first cell is filled is a group heading (a
        #   paper table's `\multicolumn{n}{l}{Cooling axis}`). Left as-is it
        #   sticks to the left cell and reads like a list item, so it is
        #   spanned across and italicized instead.
        if len(row) > 1 and str(row[0]).strip() and \
                not any(str(c).strip() for c in row[1:]):
            out.append("    \\multicolumn{%d}{l}{\\itshape %s} \\\\"
                       % (len(row), fmt(row[0], dark)))
            continue
        cells = []
        for c in row:
            lv, rest = deckspec.cell_indent(c)
            cells.append(("\\hspace*{%dem}" % lv if lv else "") + fmt(rest, dark))
        out.append("    " + " & ".join(cells) + r" \\")
    out += rule("bottomrule")
    out.append("  \\end{tabular}")
    if sz:
        out.append("  }")
    out.append("  }%")
    out.append("  \\adjustbox{max width=%s}{\\usebox{\\ptTbl}}" % fit)
    if t.get("note"):
        # A table's note is left-aligned. A table inside a column sits
        #   inside a `\centering` group, so the note would otherwise print
        #   centered too. Restored to `\raggedright` inside the group.
        # actual size = table font size x min(1, available width / table width). e-TeX's a*b/c computes the intermediate at double precision
        _nsz = ("\\begingroup\\footnotesize\\xdef\\ptFnPt{\\csname f@size\\endcsname}\\endgroup"
                "\\dimen0=\\ptTblPt pt"
                "\\ifdim\\wd\\ptTbl>%s\\relax\\dimen0=\\dimexpr\\ptTblPt pt*%s/\\wd\\ptTbl\\relax\\fi"
                "\\ifdim\\dimen0<\\ptFnPt pt\\relax\\scriptsize\\else\\footnotesize\\fi" % (fit, fit))
        out.append("\n  \\par{\\raggedright%s %s\\par}" % (_nsz, fmt((t["note"]))))
    return "\n".join(out)


def _img_path(p, base, figdir):
    """The expected path to use in a warning message: the first candidate."""
    if os.path.isabs(p):
        return p
    roots = [base] if isinstance(base, str) else list(base or [])
    return os.path.join(roots[0] if roots else "", figdir, os.path.basename(p))


def find_img(p, base, figdir):
    """Where the figure actually is. None if it is not there.

    Checks two places: where the `.tex` will be, and where the spec is.
      `\\graphicspath{{figs/}}` is resolved relative to the directory
      pdflatex runs from, so the `.tex` side is the correct answer, and the
      spec side is also checked for the common layout of keeping the spec
      and its figures in the same folder.

    It used to check only the spec side. So following the docs exactly,

        build_figs.py slides.yaml -o out/figs
        build_deck.py slides.yaml -o out/talk.tex

      puts the figures in `out/figs/`, but the check looked at `./figs/` and
      drew an empty box saying "figure not found," even though the figure
      would have come out fine once typeset. The command written in the docs
      disagreed with another line in the same docs.
    """
    if os.path.isabs(p):
        return p if os.path.isfile(p) else None
    roots = [base] if isinstance(base, str) else list(base or [])
    for r in roots:
        if not r:
            continue
        q = os.path.join(r, figdir, os.path.basename(p))
        if os.path.isfile(q):
            return q
    return None


GRID_COL_MIN = 0.14     # minimum grid column width (fraction of text width), so the header/result text fits in two lines


def grid_aspect(imgs, base, figdir):
    """A grid figure's width/height. Measured from the first figure found. None if it cannot be measured."""
    try:
        from PIL import Image
    except ImportError:
        return None
    for row in imgs:
        for src in row:
            p = find_img(src, base, figdir) if base else None
            if p:
                try:
                    with Image.open(p) as im:
                        return float(im.width) / max(1, im.height)
                except (OSError, ValueError):
                    return None
    return None


def grid_body(f, base, figdir, warn, width="\\textwidth", reserve=0.0):
    """Image grid: rows and columns get names, and each column's result gets
    an outline.

    Placing photos of the same subject under different conditions side by
      side, with an outline around the result, lets the audience see the
      difference for themselves. Without this, the spec's whole argument
      collapses into one big line of text ("Cold packs pass. Warm packs fail.").

    The outline does not use color alone. Failure is a thick solid line
      (1.2pt), success a thin one (0.5pt), the same on the PPTX side. It
      survives for an eye that cannot see the color.
    """
    g = f["grid"]
    imgs = g["images"]
    nr, nc = len(imgs), len(imgs[0])
    cols = list(g.get("cols") or [""] * nc)
    rows = list(g.get("rows") or [""] * nr)
    mark = list(g.get("mark") or [None] * nc)
    cap = list(g.get("caption") or [""] * nc)
    # The row-name column's width is subtracted first. Without subtracting
    #   it, the table runs past the line width.
    lab_frac = 0.11 if any(rows) else 0.0
    lab_w = lab_frac
    # The remaining width is split across the columns. Relative to
    # `\linewidth`, so it still fits inside a two-column layout.
    cw = "%.4f\\linewidth" % max(0.05, (1.0 - lab_frac - 0.012 * nc) / nc)
    # Height has to be bound too. Giving only the width lets the rows stack
    #   up and the last one run off the slide; pdflatex raises no error, it
    #   is only invisible. Subtracts what the header/caption/lead take up
    #   and splits the remaining height across the rows.
    #   `reserve` is what outside the grid takes up (a slide's `foot`, etc).
    #     Without subtracting it, the grid uses up all the space and pushes
    #     the text below it off the slide: fine in the `.tex`, missing from
    #     the PDF. `outcheck` caught this.
    # Computed in inches and converted to a fraction only once at the end.
    #   It used to subtract inches (`reserve`) from a fraction (0.86), so on
    #   a slide with both a lead and a foot, the rows hit the floor and the
    #   photo grid that opens the talk shrank to a thumbnail.
    room_in = (deckspec.BODY_H_IN - float(reserve or 0.0)
               - (0.17 if any(cols) else 0.0) - (0.15 if any(cap) else 0.0)
               - deckspec._lines(f.get("lead"), "lead") * deckspec.LINE_H_IN["lead"]
               - (0.17 if f.get("caption") else 0.0))
    row_frac = max(0.08, room_in / nr / deckspec.TEXT_H_TOTAL_IN)
    chh = g.get("max_height") or "%.4f\\textheight" % row_frac
    _res = deckspec.EXTRA_RESERVE.get(CURRENT_N[0], 0.0)
    if g.get("max_height") and _res > 0:
        # A directly-given cell height is also shrunk by however much it
        #   overflowed (split across the rows), since the same 14.9pt has
        #   overflowed even after two feedback passes. Same rule as a figure
        #   slide's max_height.
        chh = "\\dimexpr %s-%.2fcm\\relax" % (g["max_height"], _res * 2.54 / max(1, nr))
    # When the height runs short and the figure ends up narrower than the
    #   column, the column width is fit to the figure's width. Otherwise the
    #   gap between figures widens by that much and the row name sits one
    #   column away from the first figure. Only known in inches at full text
    #   width, so it is left as-is inside a column.
    ar = grid_aspect(imgs, base, figdir)
    if ar and width == "\\textwidth" and not g.get("max_height"):
        img_in = row_frac * deckspec.TEXT_H_TOTAL_IN * ar
        full = (1.0 - lab_frac - 0.012 * nc) / nc
        # The width a header/result text needs to fit on one line is the
        #   floor. Width does not affect height, but a wrapped line steals
        #   space from the figure: once "sold out before noon" wrapped to two
        #   lines, the figure shrank again. Text width is estimated
        #   generously at scriptsize (7pt) x 0.52em.
        lab_in = max([len(deckspec.strip_markup(str(x))) for x in cols + cap] or [0]) \
            * 0.52 * 7.0 / 72.0 + 0.06
        cw = "%.4f\\linewidth" % min(full, max(
            GRID_COL_MIN, img_in / deckspec.TEXT_W_IN + 0.012,
            lab_in / deckspec.TEXT_W_IN))

    out = []
    if f.get("lead"):
        out.append("{\\small %s}\n" % fmt((f["lead"])))
    out.append("{\\centering\\setlength{\\tabcolsep}{1pt}%")
    # Column width is fixed (`m{}`) and vertically centered. With `c`, the
    #   longest caption ends up deciding that column's width, so spacing is
    #   uneven and a row name sticks to the bottom of the image.
    spec = ((">{\\raggedleft\\arraybackslash}m{%.4f\\linewidth}" % (lab_frac - 0.012))
            if lab_w else "")
    spec += (">{\\centering\\arraybackslash}m{%s}" % cw) * nc
    out.append("\\begin{tabular}{@{}%s@{}}" % spec)
    if any(cols):
        out.append("  %s%s \\\\[1pt]"
                   % ("&" if lab_w else "",
                      " & ".join("{\\scriptsize %s}" % fmt(c) for c in cols)))
    for ri in range(nr):
        cells = []
        for ci in range(nc):
            p = imgs[ri][ci]
            missing = bool(base) and find_img(p, base, figdir) is None
            if missing and warn is not None:
                warn.append("Grid figure not found: %s" % _img_path(p, base, figdir))
            if missing:
                body = ("\\fbox{\\parbox{0.95\\linewidth}{\\centering\\scriptsize\\ttfamily "
                        "missing}}")
            else:
                # Inside a table cell, `\\linewidth` is that cell's width.
                #   Passing `cw` through as-is turns into 21% of the cell,
                #   shrinking the grid further.
                body = (IMG_GRAY + "\\adjincludegraphics[max width=\\linewidth,max height=%s]{%s}}"
                        % (chh, tex_img(p)))
            # A result mark is drawn only on the last row: that row is the result
            m = mark[ci] if ri == nr - 1 else None
            if m == "fail":
                body = ("{\\setlength{\\fboxrule}{1.2pt}\\setlength{\\fboxsep}{0pt}"
                        "\\fcolorbox{mHit}{white}{%s}}" % body)
            elif m == "ok":
                body = ("{\\setlength{\\fboxrule}{0.5pt}\\setlength{\\fboxsep}{0pt}"
                        "\\fcolorbox{mSafe}{white}{%s}}" % body)
            cells.append(body)
        out.append("  %s%s \\\\[%s]"
                   % (("{\\scriptsize %s} &" % fmt(rows[ri])) if lab_w else "",
                      " & ".join(cells), g.get("gap", "1pt")))
    if any(cap):
        out.append("  %s%s \\\\"
                   % ("&" if lab_w else "",
                      " & ".join("{\\scriptsize %s}" % fmt(c) for c in cap)))
    out.append("\\end{tabular}\\par}")
    if f.get("caption"):
        out.append("\n{\\footnotesize %s}" % fmt((f["caption"])))
    return out


def item_tex(b):
    """One bullet line. Starting with `> ` indents with no bullet mark, a clue that the list is ending."""
    txt, dot = deckspec.bullet_of(b)
    # A numbered step (`steps` -> `> 1. ...`) puts the number in the
    #   bullet-mark slot. Leaving it as one indented chunk put the second
    #   line to the left of the number. Putting it in the bullet-mark slot
    #   lines the second line up with the text.
    mn = re.match(r"(\d{1,2}\.)\s+(.*)", txt, re.S) if not dot else None
    if mn:
        return "\\item[%s] %s" % (mn.group(1), fmt(mn.group(2)))
    return ("\\item %s" % fmt(txt)) if dot else ("\\item[] \\hspace{1em}%s" % fmt(txt))


def author_tex(meta):
    """The author line. Underlined if `meta.presenter` appears in it, the convention at academic talks."""
    a = esc(meta["author"])
    p = meta.get("presenter")
    if p and esc(p) in a:
        a = a.replace(esc(p), "\\underline{%s}" % esc(p), 1)
    return a


def stacked_body(s, base, figdir, warn):
    """The figure below a diagram (one photo or a grid). Height is `deckspec.stacked_photo_in`."""
    ph = s["figure"]
    h_in = deckspec.stacked_photo_in(s)
    out = ["\\par\\vspace{0.35em}"]
    if ph.get("grid"):
        out += grid_body(ph, base, figdir, warn,
                         reserve=max(0.0, deckspec.BODY_H_IN - h_in))
        return out
    if base and find_img(ph["path"], base, figdir) is None:
        if warn is not None:
            warn.append("Figure not found: %s" % _img_path(ph["path"], base, figdir))
        out.append("\\fbox{\\ttfamily missing: %s}" % esc(ph["path"]))
    else:
        cap_in = h_in - deckspec.BODY_H_IN * float(ph.get("share") or deckspec.STACK_PHOTO_SHARE)
        # Cropping and the look-here mark use the same function. Without
        #   this, the figure was inserted directly, so `crop`/`highlight`
        #   were silently ignored and a multi-panel figure went in whole.
        #   The layout planning.md's object section recommends.
        _shown = shown_img(ph, base, figdir)
        out.append(image_tex("max width=\\textwidth,max height=%.2fcm" % ((h_in - cap_in) * 2.54),
                             crop_path(ph, base, figdir, warn), ph, _shown))
        # The band below a diagram needs to be wide and short to read.
        #   Putting in a tall figure (a whole multi-panel grid) shrinks it to
        #   fit the band's height and it becomes a thumbnail, and can drop
        #   the photo entirely. For a multi-panel grid, `crop` down to one
        #   row and it becomes a band; its width is measured and reported.
        if warn is not None and _shown:
            try:
                with deckspec._open_figure(_shown) as _im:
                    _ar = _im.width / float(max(1, _im.height))
                _w = min(deckspec.TEXT_W_IN, (h_in - cap_in) * _ar)
                if _w < 0.45 * deckspec.TEXT_W_IN:
                    warn.append("Slide %s: the figure below the diagram prints at only %d%% of the width "
                                "(aspect ratio %.2f), which is a thumbnail, not a band. For a multi-panel grid, "
                                "use `figure.crop` to cut it down to one row only so it becomes a band"
                                % (s.get("n"), round(100 * _w / deckspec.TEXT_W_IN), _ar))
            except Exception:           # an unreadable figure was already reported above
                pass
    if ph.get("caption"):
        out.append("\\par{\\scriptsize %s\\par}" % fmt(ph["caption"]))
    return out


def highlights(f, img=None):
    """`figure.highlight` -> [(x, y, w, h, label, mark)]. A fraction (0-1)
    measured from the figure's top-left corner.

    `img` is the file for the figure as shown (the cropped version, if
    cropped), used to measure where the label goes."""
    hs = (f or {}).get("highlight") or []
    hs = [hs] if isinstance(hs, dict) else list(hs)
    out = []
    for h in hs:
        try:
            out.append((float(h["x"]), float(h["y"]), float(h["w"]), float(h["h"]),
                        str(h.get("label") or ""), h.get("mark") or "plain",
                        deckspec.label_place(h, img)))
        except (KeyError, TypeError, ValueError):
            continue
    return out


def tex_img(p):
    """The figure name pdflatex will read. EPS becomes the same-named PDF `build.py` produced."""
    p = str(p)
    return p[:-4] + ".pdf" if p.lower().endswith(".eps") else p


def crop_path(f, base, figdir, warn=None):
    """The name of the cropped figure if `figure.crop` is set, otherwise the original path.

    If given `warn`, also reports whether the cut line crosses text or a
      color band. A cut-off fragment of a name and an unlabeled color bar
      have made it onto a talk slide as-is this way, caught by no check
      anywhere, visible only when a human looked at the slide.
    """
    p = f["path"]
    if f.get("crop") and base:
        src = find_img(p, base, figdir)
        if src:
            if warn is not None:
                try:
                    cuts = deckspec.crop_cuts(src, f["crop"])
                except Exception:        # an unreadable figure shows up in the cropping step itself
                    cuts = []
                side = {"left": u"left", "right": u"right", "top": u"top", "bottom": u"bottom"}
                for edge, runs, frac in cuts:
                    what = (u"crosses a filled band (%d%% of the line); if it's a color bar, the tick numbers are cut off"
                            % round(frac * 100) if frac >= 0.30 else
                            u"cuts through %d spot(s); if it's text, a fragment of a name is left" % runs)
                    msg = (u"Cropped figure %s's %s edge %s. Open the slide and check, "
                           u"then widen the crop or cut in the margin instead" % (p, side[edge], what))
                    if msg not in warn:
                        warn.append(msg)
            return os.path.basename(deckspec.crop_image(src, f["crop"]))
    return p


# A pasted figure is inserted inside a gray colorspace group. A PDF figure
#   that never sets its own colorspace (only one `0.75 sc`) can inherit
#   metropolis's RGB text color, so a gray tick mark printed red (0.75, 0, 0)
#   on a paper figure this way. It looks fine in a plain beamer or article
#   document, so no check caught it. Color is switched only inside a group.
IMG_GRAY = "{\\color{black}"


def shown_img(f, base, figdir):
    """The file path of the figure as shown on screen: the cropped version
    if cropped. None if it cannot be found."""
    try:
        src = find_img(f["path"], base, figdir) if base else None
        if src and f.get("crop"):
            src = deckspec.crop_image(src, f["crop"])
        return src
    except Exception:
        return None


def image_tex(opts, path, f=None, img=None):
    """One figure. If `highlight` is set, draws an outline on top of it.

    When a result exists only inside a paper's figure (the number is not in
      the text), there is no way to redraw it, and a number must never be
      copied over by hand. Without this, the figure never points anywhere,
      and the audience has to read all twenty bars themselves, as six
      results slides once did. One outline does that job instead.
    """
    tex = IMG_GRAY + "\\" + "adjincludegraphics[%s]{%s}}" % (opts, tex_img(path))
    hs = highlights(f, img)
    if not hs:
        return tex
    out = ["\\begin{tikzpicture}\\node[anchor=south west,inner sep=0] (im) {%s};" % tex,
           "\\begin{scope}[x={(im.south east)},y={(im.north west)}]"]
    for x, y, w, h, lab, mk, at in hs:
        # No mark means an accent color with no judgment attached. Back when
        #   red was the default, a "look here" box read as "bad." Color is
        #   used only for what the paper judged.
        col = {"hit": "mHit", "safe": "mSafe"}.get(mk, "mHi")
        y0 = 1.0 - y - h
        out.append("\\draw[%s,line width=1.4pt,rounded corners=1pt] (%.3f,%.3f) rectangle (%.3f,%.3f);"
                   % (col, x, y0, x + w, y0 + h))
        if lab:
            _anc, _py = {"above": ("south west", y0 + h), "below": ("north west", y0),
                         "inside": ("north west", y0 + h)}[at]
            # If the box sits in the figure's right half, the label aligns
            #   to the box's right edge and extends left instead: extending
            #   right can touch the title of the neighboring column outside
            #   the figure. PPTX follows the same rule.
            _lx = x
            if x + w / 2.0 > 0.5:
                _anc, _lx = _anc.replace("west", "east"), x + w
            out.append("\\node[%s,font=\\scriptsize\\bfseries,anchor=%s,fill=white,"
                       "inner sep=1pt] at (%.3f,%.3f) {%s};" % (col, _anc, _lx, _py, fmt(lab)))
    out.append("\\end{scope}\\end{tikzpicture}")
    return "".join(out)


def figure_body(f, base, figdir, warn, width="\\textwidth", height=None):
    """One figure. Passing a missing file through as-is kills pdflatex, and the whole deck fails to come out."""
    if f.get("grid"):
        return grid_body(f, base, figdir, warn, width)
    out = []
    if f.get("lead"):
        out.append("{\\small %s}\n" % fmt((f["lead"])))
    missing = False
    if warn is not None and base:
        missing = find_img(f["path"], base, figdir) is None
        if missing:
            warn.append("Figure not found: %s" % _img_path(f["path"], base, figdir))
    if missing:
        out.append("\\fbox{\\parbox{0.8\\linewidth}{\\centering\\ttfamily "
                   "missing: %s}}" % esc(f["path"]))
    else:
        out.append(image_tex("max width=%s,max height=%s"
                             % (width, height or f.get("max_height", deckspec.cm_of("figure"))),
                             crop_path(f, base, figdir, warn), f, shown_img(f, base, figdir)))
    if f.get("caption"):
        out.append("\n{\\footnotesize %s}" % fmt((f["caption"])))
    return out


BIG_COLOUR = {"hit": "mHitLt", "safe": "mSafeLt", "hi": "mHi"}


def big_body(s):
    """An impact slide's big text. One line for a single value, placed side
    by side for several.

    An impact slide can be a single "big thing," or it can be several values
      placed side by side. Collapsing side-by-side values into one big
      sentence erases the comparison, but `refcheck` counts both as "1
      impact slide." A count cannot tell the two apart.

    Spec:
        big: "31.8"                          # a single line as-is
        big:                                  # placed side by side
          - {value: "24.1", label: "Route 7",  note: "minutes late", mark: hit}
          - {value: "5.6",  label: "Route 12", note: "minutes late", mark: safe}
        gap: "3 days sooner"                  # the words to put between the two
    """
    v = s.get("big")
    # Some impact slides have only a vertical flow (`flow`). Then there is no big text.
    if not v:
        return []
    if not isinstance(v, list):
        # Markup must be unpacked. Every other piece of text in this file
        #   goes through `fmt` (esc -> markup -> minus), but this one spot
        #   was skipped, so a closing slide once printed `**shape**` with
        #   the literal asterisks. An impact slide has a dark background,
        #   so it uses `MARKS_DARK`.
        _v, _held = _hold_code(str(v))
        big = _put_code(minus(render_markup(
            esc(re.sub(r"(?<![\w.])[\u2212-](?=\d)", r"\\bigminus ", _v)),
            MARKS_DARK)), _held)
        # Size comes from the content. 40pt is only for a number; a phrase
        #   is 14pt, since impact is made by a black screen and empty space,
        #   not font size. Pinning it to a fixed 40pt let a
        #   thirty-seven-character phrase cover the whole screen.
        pt = deckspec.big_pt(v)
        return ["{\\fontsize{%.0f}{%.0f}\\selectfont %s\\par}"
                % (pt, pt * 1.16, big)]

    # Stack one cell vertically: name / big number / spec. Inside a tabular
    #   cell, `\par` does not break the line (it is in horizontal mode). It
    #   has to be stacked with a nested tabular instead. Writing it with
    #   `\par` at first lined all three up side by side and the rightmost
    #   one ran off screen.
    cells = []
    # Two values placed side by side share one size. Measuring each value
    #   separately makes "range" small and "4 pumps" big, and the size
    #   difference reads as "this one matters more." Both match the smaller one.
    _pts = []
    for b0 in v:
        b0 = b0 if isinstance(b0, dict) else {"value": b0}
        _p0 = deckspec.big_pt(b0.get("value", b0.get("text", "")))
        _pts.append(deckspec.BIG_PT_PAIRED if _p0 >= deckspec.BIG_PT_NUMBER else _p0)
    _one = min(_pts) if _pts else deckspec.BIG_PT_PAIRED
    for b in v:
        b = b if isinstance(b, dict) else {"value": b}
        col = BIG_COLOUR.get(b.get("mark"))

        def paint(x):
            return "\\textcolor{%s}{%s}" % (col, x) if col else x

        num = esc(re.sub(r"(?<![\w.])[\u2212-](?=\d)", r"\\bigminus ",
                         str(b.get("value", b.get("text", "")))))
        lines = []
        if b.get("label"):
            lines.append("{\\large %s}" % paint(fmt(b["label"], dark=True)))
        # Same rule when placed side by side: a label that is not a number is not printed large.
        pt = _one
        # The width one cell can use. Long text wraps within this width;
        #   leaving it as one line widens the cell and shrinks the whole
        #   line to fit the slide width, printing the note below the floor
        #   size and failing fitcheck. Short text is left as-is.
        _nw = (deckspec.TEXT_W_IN - (deckspec.GAP_MAX_IN if len(v) == 2 else 0.0) - 0.4) / max(1, len(v))
        _val = deckspec.plain(str(b.get("value", b.get("text", ""))))
        if deckspec.text_width_in(_val, pt) > _nw:
            lines.append(paint("\\parbox{%.2fin}{\\centering\\fontsize{%.0f}{%.0f}\\selectfont %s}"
                               % (_nw, pt, pt * 1.12, num)))
        else:
            lines.append(paint("{\\fontsize{%.0f}{%.0f}\\selectfont %s}"
                               % (pt, pt * 1.12, num)))
        if b.get("note"):
            _nt = deckspec.plain(str(b["note"]))
            if deckspec.text_width_in(_nt, 8.0) > _nw:
                lines.append("\\parbox{%.2fin}{\\centering\\footnotesize %s}"
                             % (_nw, paint(fmt(b["note"], dark=True))))
            else:
                lines.append("{\\footnotesize %s}"
                             % paint(fmt(b["note"], dark=True)))
        cells.append("\\begin{tabular}{@{}c@{}}%s\\end{tabular}"
                     % "\\\\[0.25em]".join(lines))

    # Writes "how far apart" in the middle: this is the slide's whole argument.
    # The number of cells and the number of `&` must match exactly. A
    #   mismatch kills pdflatex with `Extra alignment tab`. When a middle cell is added, the column spec grows with it.
    if len(cells) == 2:
        # The middle word is one thing. Giving `gap` stacks "or" and "vs"
        #   one above the other; both do the same job, so one of them is
        #   clutter.
        # And that one thing sits on the same line as the big numbers.
        #   Sitting on the label line instead reads like the fork in the road
        #   sits between the names, not between the values.
        _labelled = any((b if isinstance(b, dict) else {}).get("label")
                        for b in v)
        # A distance (a `gap` with a number in it) goes small, on the name
        #   line; between the numbers goes `vs`. A connector (`or`) goes
        #   between the numbers. Long text has its width bound, since
        #   without binding it, it pushes the two numbers to opposite edges
        #   of the screen.
        place = deckspec.gap_place(s.get("gap"), _labelled)
        word = fmt(s["gap"], dark=True) if s.get("gap") else "vs"
        box = "\\parbox{%.2fin}{\\centering %s}"
        if place == "label":
            mid = ("\\begin{tabular}{@{}c@{}}{\\footnotesize %s}\\\\[0.25em]"
                   "{\\normalsize vs}\\end{tabular}"
                   % (box % (deckspec.GAP_MAX_IN, word)))
        else:
            pre = "{\\large ~}\\\\[0.25em]" if _labelled else ""
            mid = ("\\begin{tabular}{@{}c@{}}%s{\\large %s}\\end{tabular}"
                   % (pre, box % (deckspec.GAP_MAX_IN, word)))
        cells = [cells[0], mid, cells[1]]
    gapspec = "@{\\hspace{1.2em}}"
    spec = gapspec.join("c" * len(cells))
    # Closes the paragraph with `\par`. Without it, the bullet that follows
    #   sticks to the side of the table and runs off screen.
    # Kept within the width. A long middle word can push the whole line
    #   past the slide width and cut off the right-hand value. `max width` only shrinks it when it overflows.
    return ["\\adjustbox{max width=\\textwidth}{\\begin{tabular}{@{}%s@{}}\n  %s\n"
            "\\end{tabular}}\\par" % (spec, " &\n  ".join(cells))]


def _slot_h(owner, where, what, slide=None):
    """A figure's `max height`, measured with the same function `build_figs` uses.

    If the two sides see different numbers, the shrinking comes back, and
      once shrinking comes back, a figure's internal text size becomes a lie
      again. So only one function is used.
    """
    sl = slide if slide is not None else owner
    pane_w = None
    if where in ("left", "right"):
        lw = float((sl.get("left") or {}).get("width") or 0.5)
        pane_w = lw if where == "left" else 1.0 - lw
    return deckspec.slot_cm(what, where, pane_w,
                            deckspec.fig_reserve(owner, where, sl))


def chart_figure(owner, where, n, slide=None):
    """Turns `chart` into the rendered figure file.

    The file is produced by `build_figs.py`. The naming convention is the
      only point of contact between the two, so changing it on only one side
      makes the figure vanish silently; if it's missing, the builder warns.
    """
    ch = owner.get("chart")
    if ch:
        return {"path": "chart_%02d_%s.png" % (n, where),
                "caption": ch.get("caption"),
                "max_height": ch.get("max_height",
                                     _slot_h(owner, where, "chart", slide))}
    # A diagram takes the same path. `build_figs` draws it and here it is
    #   seen only as a figure file: the naming convention is the only point
    #   of contact between the two, so changing it on only one side makes it
    #   vanish silently.
    d = owner.get("diagram")
    if d:
        return {"path": "diagram_%02d_%s.png" % (n, where),
                "caption": d.get("caption"),
                "max_height": d.get("max_height",
                                    _slot_h(owner, where, "diagram", slide))}
    return None


def pane_body(pane, base, figdir, warn, slide, where="self", owner=None):
    """The content of one left/right column. Text, figures, and a table can be mixed together.

    Given `parts`, blocks are stacked in that order. A column like
    "table -> one-line explanation -> box," or "subheading+text -> bullets ->
    text," where the same kind repeats or the order changes, could not be
    built with one fixed order per key; `text` always ended up at the bottom.

    `owner` is the column to look at when measuring space. A figure inside a
    block cannot look only at its own block; it also has to subtract the
    height its sibling blocks will use.
    """
    own = owner if owner is not None else pane
    if pane.get("parts"):
        out = []
        for j, p in enumerate(pane["parts"]):
            if j:
                out.append("\\par\\vspace{0.45em}")
            out += pane_body(p, base, figdir, warn, slide, where, own)
        return out
    if pane.get("size") == "fine":
        # One size smaller: an added-on note. Has to be grouped, or it leaks into the next block.
        # An inner `text` can re-apply its own size (`\footnotesize`), which
        #   would otherwise give `fine` no effect. The size is passed all the way in.
        inner = pane_body(dict({k: v for k, v in pane.items() if k != "size"},
                               _textsize="scriptsize"),
                          base, figdir, warn, slide, where, own)
        return ["{\\scriptsize"] + inner + ["\\par}"]
    out = []
    fig_of = pane.get("figure") or chart_figure(pane, where, slide["n"],
                                                slide)
    if pane.get("head"):
        # A small heading per column: this is how two subjects' tables are told apart.
        # `\\centering` is kept confined inside braces. Left outside, the
        #   rest of that column would print centered too; "`\\centering`
        #   lives until the end of its group" is already written twice in this file.
        if deckspec.head_is_caption(pane):
            out.append("{\\centering\\footnotesize %s\\par}\\vspace{0.3em}"
                       % fmt((pane["head"])))
        else:
            # A heading over text is a bold, left-aligned subheading.
            out.append("{\\small\\bfseries %s\\par}\\vspace{0.2em}"
                       % fmt((pane["head"])))
    # `\centering` stays in effect until the end of its group. Left as a
    #   plain line, the note that follows the table would get centered too.
    #   Confined inside braces instead.
    if fig_of:
        out.append("{\\centering")
        out += figure_body(fig_of, base, figdir, warn,
                           width="\\linewidth",
                           height=fig_of.get("max_height",
                                          _slot_h(own, where, "diagram", slide)))
        out.append("\\par}")
    # If a chart was already drawn from this column's own table, the table
    #   itself is not printed. Printing both puts the same data in one
    #   column twice, exactly the shape `refcheck` fails; the slide level already does this.
    chart_ate_it = (pane.get("chart") is not None
                    and pane["chart"].get("from", "self") == "self")
    if pane.get("table") and not chart_ate_it:
        out.append("{\\centering")
        out.append(render_table(pane["table"], warn,
                                slide.get("title") or "slide %d" % slide["n"],
                                fit="\\linewidth",
                                # A table inside a column is a reference table of "every case -> how many": no leaderboard warning applies
                                main=False))
        out.append("\\par}")
    if pane.get("bullets"):
        out.append("\\begin{itemize}")
        for b in pane["bullets"]:
            out.append("  " + item_tex(b))
        out.append("\\end{itemize}")
    if pane.get("block"):
        # A highlight box inside a column: used to attach a warning like "what this doesn't explain" to only one side
        # A block inside a column is the same size as the column's text.
        #   Without setting the size, the block's text would print one size
        #   larger than the neighboring column's text. If the column is
        #   `fine`, it follows that.
        out += [x.strip() for x in block_body({"block": pane["block"]},
                                              size=pane.get("_textsize", "footnotesize"))]
    if pane.get("text"):
        # `text` is that column's footnote. Placed above a table or figure,
        #   the reading order comes out wrong.
        #   Given as a list, the line breaks are set explicitly. Left as
        #     one block, it wraps however it wraps and the author's chosen line breaks are lost.
        lines = pane["text"]
        lines = [lines] if isinstance(lines, str) else list(lines)
        out.append("\\par\\vspace{0.4em}")
        out.append("{\\%s %s\\par}"
                   % (pane.get("_textsize", "footnotesize"),
                      "\\\\\n  ".join(fmt((x)) for x in lines)))
    return out


BLOCK_ENV = {"plain": "block", "alert": "alertblock", "good": "exampleblock"}


def foot_body(s):
    """The full-width fine print under the body. This is how a caption or
    legend under a table/figure is attached."""
    if not s.get("foot"):
        return []
    # `\centering` lives until the end of its group. A footnote that comes
    #   after a figure or table would otherwise print centered, and the
    #   moment it ran past one line the right edge got ragged. Trying to fix
    #   it by grouping the figure side made the table inside `adjustbox`
    #   vanish, so it is reverted on the receiving side instead.
    out = ["  \\par\\vspace{0.35em}", "  {\\raggedright\\footnotesize"]
    out += ["  %s\\\\" % fmt((x)) for x in s["foot"][:-1]]
    # `\\par` has to sit inside the closing brace. Outside it, TeX composes
    #   the paragraph with the alignment from outside the group (the earlier
    #   `\\centering`), so it prints centered even with `\\raggedright`
    #   turned on. This has really happened.
    out.append("  %s\\par}" % fmt((s["foot"][-1])))
    return out


def fine_body(s):
    """One step smaller than a footnote, the last block: notation, definitions, caveats.

    A concluding sentence (footnotesize) and a pile of notation (scriptsize)
      are stacked at different weights. Lumped into one weight, "the
      sentence to read first" and "what to look up when needed" look the
      same, and then the audience reads neither.
    """
    if not s.get("fine"):
        return []
    out = ["  \\par\\vspace{0.25em}", "  {\\raggedright\\scriptsize"]
    out += ["  %s" % fmt((x)) for x in s["fine"][:-1]]
    # `\\par` goes inside the closing brace. Same reason as `foot_body`.
    out.append("  %s\\par}" % fmt((s["fine"][-1])))
    return out


def block_body(s, size=None):
    """Under metropolis's `block=fill`, a block with no title becomes an
    empty gray band. The spec requires a title, so this uses it as given.
    If `size` is given, the block's text is set at that size."""
    b = s.get("block")
    if not b:
        return []
    env = BLOCK_ENV[b.get("kind", "plain")]
    body = fmt((b.get("text") or ""))
    if size:
        body = "{\\%s %s\\par}" % (size, body)
    return ["  \\par\\vspace{0.4em}",
            "  \\begin{%s}{%s}" % (env, fmt((b["title"]))),
            "    %s" % body,
            "  \\end{%s}" % env]


def guard_group(body):
    """A frame body that starts with `{` turns into a blank slide. A space
    is inserted in front of it.

    An opening evidence slide has come out entirely blank this way, with no
      figure, no row/column names, no error, not one line in the log. The
      condition is narrow (with a `lead`, the text comes first; with no
      bullets, `\\vfill` comes first), so it is easy to miss.

    This skill already knew about this bug: the `standout` path already says
      "without it, the next `{..}` gets eaten as the frametitle." The
      problem was that the guard existed on only that one path. So this
      blocks it in this one place instead. A new layout is protected automatically.
    """
    for i, line in enumerate(body):
        s = line.strip()
        if not s or s.startswith("\\begin{frame}"):
            continue
        if s.startswith("{"):
            body.insert(i, "  \\vspace{0pt}%")
        break
    return body


CURRENT_N = [None]


def render(s, base=None, figdir="figs", warn=None):
    """One slide into LaTeX. Given `warn`, a missing figure is recorded there."""
    k = s["kind"]
    body = []
    CURRENT_N[0] = s.get("n")        # so a place that does not know its own slide, like a grid, can find the overflow feedback

    if k == "standout":
        # `plain` is given alongside it. Without it, metropolis prints the
        #   page number in dark text on the dark background: invisible to
        #   the eye but still present in the PDF's text layer, and that value
        #   is the stale number from one slide back. A checker once read that
        #   as the page number and threw 17 failures on a perfectly fine
        #   deck. Text nobody can see should be removed.
        body.append("\\begin{frame}[standout,plain]")
        # Without it, the next `{..}` gets eaten as the frametitle
        body.append("  \\vspace{0pt}%")
        if s.get("lead"):
            body.append("  {\\large %s\\par}" % fmt(s["lead"], dark=True))
            body.append("  \\par\\vspace{0.8em}")
        body += ["  " + x for x in big_body(s)]
        # A vertical flow: step, down-arrow, step, down-arrow, last step.
        #   `big` places things side by side, but this runs top to bottom
        #   instead. At a turning point, it lays out "what goes to what" on one screen.
        if s.get("flow"):
            fl = list(s["flow"])
            for j, step in enumerate(fl):
                last = (j == len(fl) - 1)
                if j:
                    body.append("  \\par\\vspace{0.45em}")
                    body.append("  {\\Large $\\Downarrow$\\par}")
                    body.append("  \\par\\vspace{0.35em}")
                else:
                    body.append("  \\par\\vspace{0.7em}")
                # The last step (where the flow arrives) is green. If the
                #   author already gave it a mark, that is followed instead.
                if last and not deckspec.emphasis(step):
                    txt = "\\textcolor{mSafeLt}{%s}" % fmt("**%s**" % step, dark=True)
                else:
                    txt = fmt(("**%s**" % step) if last else step, dark=True)
                body.append("  {%s %s \\par}"
                            % ("\\Large" if last else "\\small", txt))
        # An impact slide sometimes has a table too: the place to write what
        #   differed underneath two big numbers. Without it, "what differed"
        #   is lost entirely.
        if s.get("table"):
            body.append("  \\par\\vspace{0.7em}")
            body.append(render_table(s["table"], warn,
                                     s.get("big", ""), dark=True))
        if s.get("bullets"):
            body.append("  \\par\\vspace{1.0em}")
            # This is a dark background. Dark red/green is unreadable here.
            body.append("  {\\large %s\\par}"
                        % fmt(" ".join(s["bullets"]), dark=True))
        # Each line separately, each at its own size: a size is set per line and they stack top to bottom.
        for j, (txt, size) in enumerate(deckspec.standout_lines(s)):
            body.append("  \\par\\vspace{%s}" % ("0.8em" if j == 0 else "0.35em"))
            body.append("  {\\%s %s\\par}" % (size, fmt(txt, dark=True)))
        body.append("\\end{frame}")
        return "\n".join(guard_group(body))

    if k == "columns":
        # One example deck had roughly one slide in three (35%) as a
        #   two-column layout. "Don't hide the table, put it next to the
        #   text" is impossible without this layout.
        body.append(frame_title(s).rstrip("\n"))
        body += lead_body(s)
        body += formula_body(s)
        # There really are slides that put a full-width figure above two
        #   columns. It's a layout where one figure serves both columns'
        #   explanations at once; without this, that slide could not be built at all.
        # Not only `figure`: `chart`/`diagram` also get placed full-width.
        #   `RENDERS["columns"]` allows all three, and PPTX draws all three,
        #   but here only `figure` was handled, so a layout the docs
        #   recommend existed in PowerPoint but not in the PDF.
        top = s.get("figure") or chart_figure(s, "self", s["n"], s)
        if top:
            # Set by measuring the height. It used to use a fixed 3.8cm,
            #   which meant the figure took up the same space whether the
            #   two columns below held four lines each or only one, and the
            #   bottom got cut off. This skill gathered its space
            #   calculations into one place, `deckspec.slot()`, and this was the one spot left outside it.
            pane_need = max(deckspec.fig_reserve(s.get(sd) or {})
                            for sd in ("left", "right"))
            top_h = top.get("max_height") or deckspec.slot_cm(
                "chart", "self", None,
                deckspec.fig_reserve(s, "self", s) + pane_need)
            body.append("  \\centering")
            body += ["  " + x for x in
                     figure_body(top, base, figdir, warn, height=top_h)]
            body.append("  \\par\\vspace{0.3em}")
        lw = float(s["left"].get("width") or 0.5)
        body.append("  \\begin{columns}[T,onlytextwidth]")
        for side, w in (("left", lw), ("right", 1.0 - lw)):
            pane = s[side]
            body.append("    \\begin{column}{%.3f\\textwidth}" % (w - 0.02))
            body += ["  " + x for x in pane_body(pane, base, figdir, warn, s, side)]
            body.append("    \\end{column}")
        body.append("  \\end{columns}")
        body += foot_body(s)
        body += fine_body(s)
        body += block_body(s)
        body.append("\\end{frame}")
        if s.get("note"):
            body.append("\\note{%s}" % esc(s["note"]))
        return "\n".join(guard_group(body))

    body.append(frame_title(s).rstrip("\n"))
    body += lead_body(s)
    body += formula_body(s)
    # A slide with only a table or figure, left at Beamer's default
    #   (top-aligned), leaves the bottom hollow and empty. Projected, that
    #   empty space shows exactly as-is. Pushed to center with `\vfill` above and below.
    sparse = k in ("figure", "table") and not s.get("bullets")
    if sparse:
        body.append("  \\vfill")
    if k == "figure" and (s.get("figure") or {}).get("grid") \
            and not deckspec.stacked(s):
        # A grid is drawn in exactly one place, `grid_body`. Putting a
        #   second implementation here is guaranteed to drift apart: the
        #   one-figure path below already overlaps with `figure_body`, and
        #   that is why this function crashed on a figure with no `path`.
        body += ["  " + x for x in
                 grid_body(s["figure"], base, figdir, warn,
                           # Counts lines, not items. When one item wraps to
                           #   two lines, only one line's worth got
                           #   subtracted, and `fine` was not counted at all:
                           #   the opening slide overflowed by 38.5pt and
                           #   the footnote dropped out of the PDF entirely.
                           reserve=deckspec.fig_reserve(s))]
    elif k == "figure":
        # When there is both a diagram and a figure, diagram on top, figure
        #   below. Until now, only the figure was drawn and the diagram was silently dropped.
        _stk = deckspec.stacked(s)
        f = (chart_figure(s, "self", s["n"], s) if _stk
             else s.get("figure") or chart_figure(s, "self", s["n"], s))
        # Must not be grouped with `{\centering ...}` here. Grouping it made
        #   the table inside `adjustbox` vanish entirely (confirmed with a
        #   minimal example). The alignment of the footnote that follows is reverted by `foot_body`.
        body.append("  \\centering")
        if f.get("lead"):
            body.append("  {\\small %s}\n" % fmt((f["lead"])))
        # Passing a missing figure through as-is kills pdflatex. Reserves
        #   the space and reports it instead: one empty box and a warning
        #   beats the whole deck failing to come out.
        missing = False
        if warn is not None and base:
            missing = find_img(f["path"], base, figdir) is None
            if missing:
                warn.append("Figure not found: %s" % _img_path(f["path"], base, figdir))
        if missing:
            body.append("  \\fbox{\\parbox{0.6\\textwidth}{\\centering\\ttfamily "
                        "missing: %s}}" % esc(f["path"]))
        else:
            # Overflow feedback (`EXTRA_RESERVE`) is given to a pasted
            #   figure too. Shrinking only generated figures left a
            #   pasted-figure slide overflowing by the same 11.5pt even
            #   after three feedback passes. A directly-given height is left as-is.
            _res = deckspec.EXTRA_RESERVE.get(s["n"], 0.0)
            _slot_h = deckspec.SLOT_H_IN["figure"]
            if _res > 0:
                # A figure bound by its width does not shrink even when the
                #   height cap is lowered: the width limit already draws it
                #   shorter than the cap. The same 15.9pt has overflowed
                #   even after two feedback passes. Subtracts the overflow
                #   from the height it actually renders at (width / aspect ratio).
                try:
                    from PIL import Image as _Im
                    _src = find_img(crop_path(f, base, figdir), base, figdir) if base else None
                    if _src:
                        with _Im.open(deckspec.crop_image(_src, f["crop"]) if f.get("crop")
                                      else _src) as _im:
                            _slot_h = min(_slot_h, deckspec.TEXT_W_IN * _im.height / max(1, _im.width))
                except Exception:
                    pass
            _fh = f.get("max_height") or "%.2fcm" % (max(
                1.0, _slot_h - _res) * 2.54)
            if f.get("max_height") and _res > 0:
                # A directly-given height is also shrunk by however much it
                #   overflowed: giving a cap without this blocked the
                #   feedback and left it "still overflowing after two
                #   feedback passes." A given value is a cap, not a fixed value.
                _fh = "\\dimexpr %s-%.2fcm\\relax" % (f["max_height"], _res * 2.54)
            body.append("  " + image_tex("max width=\\textwidth,max height=%s" % _fh,
                                         crop_path(f, base, figdir, warn), f,
                                         shown_img(f, base, figdir)))
        if f.get("caption"):
            body.append("\n  {\\footnotesize %s}" % fmt((f["caption"])))
        if _stk:
            body += ["  " + x for x in stacked_body(s, base, figdir, warn)]
    elif k == "table":
        body.append("  \\centering")
        body.append(render_table(s["table"], warn, s.get("title") or "slide %d" % s["n"],
                                 main=not s.get("backup")))
    if s.get("bullets") and k != "standout":
        body.append("  \\begin{itemize}")
        for b in s["bullets"]:
            body.append("    " + item_tex(b))
        body.append("  \\end{itemize}")
    body += foot_body(s)
    body += fine_body(s)
    body += block_body(s)
    if sparse:
        body.append("  \\vfill")
    body.append("\\end{frame}")

    if s.get("note"):
        # A note is not part of the screen. A checker strips it out by matching braces.
        body.append("\\note{%s}" % esc(s["note"]))
    return "\n".join(guard_group(body))


def build(spec_path, out_path, figdir=None):
    meta, slides, npage = load(spec_path)
    ratio = str(meta.get("aspect", "16:9")).replace(":", "")
    engine = str(meta.get("engine") or "pdflatex").lower()
    if engine not in ENGINES:
        raise ValueError("meta.engine must be one of %s (got %r)"
                         % ("/".join(sorted(ENGINES)), meta.get("engine")))
    head = PREAMBLE % {
        "ratio": ratio,
        # Color comes from a single place, `design.py`. Writing it
        #   separately here would drift from the figures and the PPTX, and
        #   nobody would notice while the values happen to still match.
        "c_hi": design.HI_TEXT.lstrip("#"),
        "c_hit": design.text_of("hit").lstrip("#"),
        "c_safe": design.text_of("safe").lstrip("#"),
        "c_hit_lt": design.text_of("hit", dark_bg=True).lstrip("#"),
        "c_safe_lt": design.text_of("safe", dark_bg=True).lstrip("#"),
        "c_block": design.NEUTRAL_FILL.lstrip("#"),
        # Body text size is decided by `deckspec`; figures read the same number.
        "basept": int(meta.get("base_pt", 10)),
        "fonts": ENGINES[engine] % {"cjkfont": meta.get("cjk_font")
                                    or "Malgun Gothic"}
        if engine == "xelatex" else ENGINES[engine],
        "figdir": str(figdir or meta.get("figdir") or "figs").replace(chr(92), "/") + "/",
        "title": esc(meta.get("title", "Untitled")),
        "subtitle": "\\subtitle{%s}" % esc(meta["subtitle"]) if meta.get("subtitle") else "",
        "author": "\\author{%s}" % author_tex(meta) if meta.get("author") else "",
        "institute": ("\\institute{%s}" % "\\\\".join(
                          esc(x) for x in deckspec.institute_lines(meta))
                      if meta.get("institute") else ""),
        "venue": "\\date{%s}" % esc(meta["venue"]) if meta.get("venue") else "\\date{}",
    }
    warn = []
    deckspec.LABEL_COVERED.clear()
    # If the cover title runs past two lines, its trailing qualifier (after
    #   a colon or preposition) is moved down to the subtitle. A three-line
    #   title covers the title slide and blurs what the subject is.
    _tt = str(meta.get("title") or "")
    # By line count measured with the title-slide font, not character count:
    #   a 75-character title once fit on two lines, but this said "past two
    #   lines" anyway. A cover title is \Large (14.4pt), bold, at the body width.
    _tl = deckspec.wrap_count(_tt, deckspec.TEXT_W_IN, 14.4, True, "Arial") if _tt else 0
    if _tl > 2 and len(_tt) > deckspec.TITLE_PAGE_CHARS and not meta.get("subtitle"):
        _cut = re.search(r"\s(in|for|with|via|on|at|of|by|under)\s", _tt[20:], re.I)
        warn.append(u"Cover title is %d characters and runs past two lines. Move %sto the "
                    u"subtitle (`subtitle`). The title is the claim, the subtitle is the scope."
                    % (len(_tt), (u"the part starting at \"%s ...\" " % _cut.group(1)) if _cut else u"the trailing qualifier "))
    # Where to look for a figure: where the `.tex` will sit comes first.
    #   `\graphicspath` is resolved relative to the directory pdflatex runs
    #   from, so that side is what pdflatex actually sees; the spec folder
    #   is also checked for the layout that keeps the spec and its figures together.
    base = (os.path.dirname(os.path.abspath(out_path)),
            os.path.dirname(os.path.abspath(spec_path)))
    fd = figdir or meta.get("figdir") or "figs"
    # With forward slashes. Passing Windows's `out` + `\\` + `figs` through
    #   as-is turns `\\`+`figs` into an undefined command, and the PDF comes
    #   out with no figures. TeX takes `/`.
    fd = str(fd).replace(chr(92), "/")
    parts = [head]
    spare = False
    for s in slides:
        if s["kind"] == "title":
            continue                      # \maketitle already emitted it
        # `\appendix` is emitted before the backup slides. Without it,
        #   beamer counts its own way and numbers the backup slides too,
        #   folding them into the denominator, so the deck says `1/4`, PPTX
        #   says `1/2`, and the spec says "a backup slide gets no number":
        #   three different stories. They diverge, and no check compared any two of them.
        if s.get("backup") and not spare:
            parts.append("\\appendix")
            spare = True
        parts.append(render(s, base, fd, warn))
        parts.append("")
    parts.append("\\end{document}")
    # Non-ASCII kills the compile in pdflatex. This says so here instead of
    #   making someone read the log. But it looks only at the body, with
    #   comments and the preamble excluded, since pdflatex does not even
    #   read comments. Scanning the whole thing at first flooded this file's
    #   own comments with false positives.
    #   `\note{}` is excluded too: it is an instruction for the presenter,
    #     never shown on screen, and pdflatex does not read it either.
    #     Korean text in a note is normal. Without excluding it, every one of them is a false positive.
    from deckcheck import strip_braced          # do not keep two copies of the same implementation
    body = "\n".join(re.sub(r"(?<!\\)%.*", "", strip_braced(p, "note"))
                     for p in parts[1:])
    # Preamble text like `meta.title` is checked too. It used to check only
    #   `parts[1:]`, so a deck with a Korean title came out with zero
    #   warnings, even though pdflatex's first six errors were all that
    #   title. The scaffold generator puts the manuscript's title straight
    #   into `meta.title`, and only the check was not looking there.
    meta_txt = " ".join(str(meta.get(k) or "") for k in
                        ("title", "subtitle", "author", "institute", "venue"))
    if engine == "pdflatex":
        symbols(body + "\n" + meta_txt, warn, "deck")
    spit(out_path, "\n".join(parts) + "\n")
    # A list of labels deliberately placed over a figure: fitcheck excludes these from overlap-over-figure
    _labs = deckspec.highlight_labels(slides)
    _hl = os.path.join(os.path.dirname(os.path.abspath(out_path)), figdir or "figs",
                       deckspec.HIGHLIGHT_LIST)
    if _labs or os.path.exists(_hl):
        os.makedirs(os.path.dirname(_hl), exist_ok=True)
        spit(_hl, "\n".join(_labs) + ("\n" if _labs else ""))
    # Page numbers of backup slides: one slide is one page. fitcheck counts
    #   small text on a backup slide as informational instead of a failure,
    #   for a slide that keeps an un-redrawable paper figure around for Q&A.
    _bk = os.path.join(os.path.dirname(_hl), deckspec.BACKUP_LIST)
    _pages = [str(i + 1) for i, s in enumerate(slides) if s.get("backup")]
    if _pages or os.path.exists(_bk):
        os.makedirs(os.path.dirname(_bk), exist_ok=True)
        spit(_bk, "\n".join(_pages) + ("\n" if _pages else ""))
    # Pages where a pasted paper figure has a look-here mark: fitcheck counts that figure's tick-mark text as informational
    _hf = os.path.join(os.path.dirname(_hl), deckspec.HLFIG_LIST)
    _hpages = [str(i + 1) for i, s in enumerate(slides) if deckspec.pasted_with_highlight(s)]
    if _hpages or os.path.exists(_hf):
        os.makedirs(os.path.dirname(_hf), exist_ok=True)
        spit(_hf, "\n".join(_hpages) + ("\n" if _hpages else ""))
    for lab, at, ink in dict(((l, a), (l, a, k)) for l, a, k in deckspec.LABEL_COVERED).values():
        warn.append(u"Highlight label \"%s\" sits over text/lines inside the figure (placed %s, %d%% ink); there "
                    u"is no empty spot above, below, or inside. Move it with `label_at`, or drop the label and say it in one `lead` line"
                    % (lab[:40], {"above": "above", "below": "below", "inside": "inside"}.get(at, at),
                       round(100 * ink)))
    return npage, len(slides), warn


def main(argv=None):
    ap = argparse.ArgumentParser(description="slides.yaml -> Beamer talk.tex")
    ap.add_argument("spec")
    ap.add_argument("-o", "--out", default="talk.tex")
    ap.add_argument("--figdir", default=None)
    a = ap.parse_args(argv)
    npage, n, warn = build(a.spec, a.out, a.figdir)
    print("=> %s  (%d slides, %d numbered)" % (a.out, n, npage))
    for w in warn:
        print("   %s" % w)
    return 0


if __name__ == "__main__":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8")
    sys.exit(main())
