# -*- coding: utf-8 -*-
"""`slides.yaml` -> `script.md` (the script the presenter holds and reads from).

    python scripts/build_script.py slides.yaml -o out/script.md
    python scripts/build_script.py slides.yaml -o out/script.md --thumbs out/talk.pdf

For each slide: (1) what to say out loud, (2) action/tone cues, (3) translation (if any),
(4) running time. A full time summary follows at the end.

Thumbnails: pass `--thumbs talk.pdf` to render the deck to per-page PNGs and hang them next
to each slide's script, so the screen brings the script to mind. This only works when
PyMuPDF is installed; if it isn't, the tool says so instead of silently skipping it.

Time is counted by `timing.py`, which converts numbers and abbreviations into a spoken
word count. Eyeballing it has been unreliable in this project.
"""
import argparse
import io
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import deckspec
from deckspec import load, spit, plain  # noqa: E402
import timing  # noqa: E402


def thumbs(pdf_path, out_dir, dpi=110):
    """Renders the deck PDF to per-page PNGs. Returns {page number: relative path}, or None."""
    try:
        try:
            import pymupdf as fitz
        except ImportError:      # PyMuPDF before 1.24.3 has only the old import name
            import fitz
    except ImportError:
        return None
    os.makedirs(out_dir, exist_ok=True)
    # Deletes thumbnails from the previous build. If the deck shrinks, an old page (s28) is
    # left behind, and its picture bleeds into a different deck.
    for old in os.listdir(out_dir):
        if re.match(r"s\d+\.png$", old):
            try:
                os.remove(os.path.join(out_dir, old))
            except OSError:
                pass
    doc = fitz.open(pdf_path)
    got = {}
    for i, page in enumerate(doc, 1):
        p = os.path.join(out_dir, "s%02d.png" % i)
        page.get_pixmap(dpi=dpi).save(p)
        got[i] = p
    doc.close()
    return got


# The script is paper the presenter holds in hand: write even the scaffolding text in
# the deck's language.
LABELS = {
    "ko": {
        "title": u"%s — 발표 대본",
        "generated": u"> 이 파일은 `build_script.py` 가 `slides.yaml` 에서 생성한다. "
                     u"손으로 고치지 말 것 — 덱·PPTX 와 갈라진다.",
        "no_pdf": u"\n> 썸네일: `%s` 가 없다. 덱을 먼저 만들어라.\n",
        "no_fitz": u"\n> 썸네일: PyMuPDF 가 없다 — `pip install pymupdf`\n",
        "total": u"**전체 %s** (말 %s + 침묵 %s · %d wpm 기준)",
        "spare_note": u"예비 장 %d장은 시간에 넣지 않았다 — 질문이 나올 때만 편다.",
        "this": u"이 장 %ds",
        "pause": u"  ·  침묵 %ds",
        "spare_head": u"# 예비 장 (본편 뒤)",
        "spare_body": u"질문이 나오면 편다. 쪽번호도 발표 시간도 붙지 않는다.",
        "asks": u"# 나올 법한 질문",
        "ask_where": u"%d장",
        "page": u"화면 %d/%d",
    },
    "en": {
        "title": u"%s — speaker script",
        "generated": u"> Generated by `build_script.py` from `slides.yaml`. "
                     u"Do not edit by hand — it would drift from the deck and the PPTX.",
        "no_pdf": u"\n> Thumbnails: `%s` not found. Build the deck first.\n",
        "no_fitz": u"\n> Thumbnails: PyMuPDF is missing — `pip install pymupdf`\n",
        "total": u"**Total %s** (speech %s + pauses %s · at %d wpm)",
        "spare_note": u"%d backup slide(s) are not in the time — open them only for questions.",
        "this": u"this slide %ds",
        "pause": u"  ·  pause %ds",
        "spare_head": u"# Backup slides (after the talk)",
        "spare_body": u"Open these when a question calls for them. They carry no page number and no time.",
        "asks": u"# Likely questions",
        "ask_where": u"slide %d",
        "page": u"screen %d/%d",
    },
}
_HANGUL = re.compile(u"[가-힣]")


def script_lang(meta, slides):
    """Uses `meta.lang` if it is set; otherwise picks by whether Hangul makes up more than
    half the letters in `say`."""
    lang = str((meta or {}).get("lang") or "").lower()[:2]
    if lang in LABELS:
        return lang
    said = " ".join(str(x) for s in slides for x in (s.get("say") or []))
    letters = re.findall(u"[A-Za-z가-힣]", said)
    if not letters:
        return "ko"
    return "ko" if len(_HANGUL.findall(said)) * 2 > len(letters) else "en"


def heading(s):
    """Script subheading: a one-liner that lets the presenter tell which slide this is at a
    glance.

    A facing impact slide uses `lead` (that slide's question or claim). Stringing together
    every value, name, and note produces an unreadable single line like "standard, ms 41.7
    (66.6 GFLOPs · ...)  more FLOPs, less time  ...". Without a `lead`, it joins only the
    value and the name.
    """
    if s.get("title"):
        return s["title"]
    big = s.get("big")
    if isinstance(big, list) and s.get("lead"):
        return s["lead"]
    if isinstance(big, list):
        bits = []
        for b in big:
            b = b if isinstance(b, dict) else {"value": b}
            v = str(b.get("value", b.get("text", "")))
            bits.append(("%s %s" % (b["label"], v)) if b.get("label") else v)
        sep = str(s.get("gap")).strip() if s.get("gap") and len(bits) == 2 else "vs"
        return ("  %s  " % sep).join(x for x in bits if x)
    return deckspec.big_text(big, s.get("gap")) or ""


def build(spec_path, out_path, pdf=None, wpm=None):
    meta, slides, _ = load(spec_path)
    rate = wpm or meta.get("wpm", 135)
    # The word value of an abbreviation is recorded in the spec (`meta.acronyms`), not in the
    # script: the script must not be hand-edited, so there has to be another place to put it,
    # or the seconds it accounts for go uncounted.
    acro = deckspec.acronyms(meta) or None
    T = LABELS[script_lang(meta, slides)]

    th = None
    note_th = ""
    if pdf:
        if not os.path.isfile(pdf):
            note_th = T["no_pdf"] % pdf
        else:
            th = thumbs(pdf, os.path.join(os.path.dirname(out_path) or ".", "thumbs"))
            if th is None:
                note_th = T["no_fitz"]

    L = ["# " + T["title"] % meta.get("title", "Untitled"), ""]
    if meta.get("venue"):
        L.append("%s" % meta["venue"])
    L.append("")
    L.append(T["generated"])
    L.append(note_th)

    # Backup slides do not count toward the talk time. They are opened only when a question
    # calls for them, so mixing them into the total would throw off the whole time calculation.
    main_ = [s for s in slides if not s.get("backup")]
    spare = [s for s in slides if s.get("backup")]
    total = 0.0
    rows = []
    for s in main_:
        # Adds up a value rounded to whole seconds for each slide. Rounding the per-slide
        # seconds while adding the running total as a float let the sum of the per-slide
        # seconds and the running total drift apart by one second.
        sec = float(int(round(timing.seconds(s["say"], s["pause"], rate, table=acro))))
        total += sec
        rows.append((s, sec, total))

    L.append("")
    L.append(T["total"]
             % (timing.hhmm(total),
                timing.hhmm(total - sum(int(s["pause"]) for s in main_)),
                timing.hhmm(sum(s["pause"] for s in main_)), rate))
    if spare:
        L.append("")
        L.append(T["spare_note"] % len(spare))
    L.append("")
    L.append("---")

    _pages = max([s.get("page") or 0 for s in slides] or [0])
    for s, sec, run in rows:
        L.append("")
        # The title slide has no title/big. A blank heading ("## 1. ") left in the script looks bad.
        # An impact slide with no title (only flow) falls back to lead, or the first flow entry,
        # so a blank heading is never left behind.
        label = heading(s) or (
            meta.get("title", "") if s["kind"] == "title" else "") or \
            s.get("lead") or ((s.get("flow") or [""])[0])
        # Renders the title's math as plain text, so `$\hat g$` does not survive raw at the
        # top of the script.
        head = "## %d. %s" % (s["n"], deckspec.plain(label))
        # Also records the on-screen page number. The script counts slides in sequence
        # (including the title and impact slides), while the screen only numbers slides that
        # carry a page number; without this, the two would disagree and be hard to line up.
        if s.get("page") is not None:
            head += "  ·  " + T["page"] % (s["page"], _pages)
        L.append(head)
        L.append("")
        L.append("`%s`  %s%s" % (timing.hhmm(run), T["this"] % int(round(sec)),
                                 T["pause"] % int(s["pause"]) if s["pause"] else ""))
        # The title and impact slides also get a thumbnail. They have no page number, but the
        # screen still exists.
        if th and s["n"] in th:
            L.append("")
            L.append("![](%s)" % os.path.relpath(
                th[s["n"]], os.path.dirname(out_path) or ".").replace("\\", "/"))
        # `note` is an action/tone cue. Putting it only in the deck's or PPTX's notes pane and
        # leaving it out of the script means it is missing from the paper the presenter holds.
        # It has to appear in all three deliverables.
        for c in ([s["note"]] if s.get("note") else []) + s["cue"]:
            L.append("")
            L.append("> %s" % plain(c))
        if s["say"]:
            L.append("")
            for x in s["say"]:
                L.append(plain(x))
                L.append("")
        if s["ko"]:
            for x in s["ko"]:
                L.append("*%s*" % plain(x))
                L.append("")
        L.append("---")

    # ── Backup slides ────────────────────────────────────────────────────────
    if spare:
        L += ["", T["spare_head"], "", T["spare_body"], ""]
        for s in spare:
            L.append("## %s" % deckspec.plain(heading(s)))
            L.append("")
            if th and s["n"] in th:
                L.append("![](%s)" % os.path.relpath(
                    th[s["n"]], os.path.dirname(out_path) or ".").replace("\\", "/"))
                L.append("")
            # Main slides carried `note`/`cue`, but backup slides were missing them. Backup
            # slides are opened right after a question comes in, when they need the cues most.
            for c in ([s["note"]] if s.get("note") else []) + s["cue"]:
                L.append("> %s" % plain(c))
                L.append("")
            for x in s["say"] + s["ko"]:
                L.append(plain(x))
                L.append("")
            L.append("---")

    # ── Likely questions ──────────────────────────────────────────────────────
    # A talk ends with questions. Writing `ask:` on each slide collects them all here in one
    # place, so there is a single spot to read right before the talk.
    asks = [(s, x) for s in slides for x in (s.get("ask") or [])]
    if asks:
        L += ["", T["asks"], ""]
        for s, x in asks:
            where = heading(s)
            # Given {q, a}, shows the question and answer side by side.
            if isinstance(x, dict):
                q, a = plain(str(x.get("q", ""))), plain(str(x.get("a", "")))
                L.append("- **%s**  <!-- %s · %s -->" % (q, T["ask_where"] % s["n"],
                                                      plain(where)))
                if a:
                    L.append("  %s" % a)
                continue
            L.append("- **%s**  <!-- %s · %s -->" % (plain(x), T["ask_where"] % s["n"],
                                                  plain(where)))
        L.append("")

    spit(out_path, "\n".join(L).rstrip() + "\n")
    return total, len(slides), th


def spoken_text(spec_path):
    """For the audience panel: only what is spoken aloud. Only the slide number and `say`;
    cues, notes, time, backup slides, and likely questions are all left out.

    audience-panel.md says stage directions cannot be heard, and that the panel chair should
    not see the time calculations. The script bakes in cues (`>`) and a running time, so this
    strips them out.
    """
    _, slides, _ = load(spec_path)
    out = []
    for s in slides:
        if s.get("backup"):
            continue
        out.append("## Slide %s" % s.get("n"))
        out.append("")
        out += [str(x) for x in (s.get("say") or [])]
        out.append("")
    return chr(10).join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(description="slides.yaml -> script.md")
    ap.add_argument("spec")
    ap.add_argument("-o", "--out", default="script.md")
    ap.add_argument("--thumbs", default=None, metavar="TALK_PDF",
                    help="renders the deck PDF to per-page PNGs and hangs them in the script")
    ap.add_argument("--wpm", type=int, default=None)
    ap.add_argument("--limit", type=float, default=None, metavar="MIN",
                    help="talk length in minutes. If it goes over, it fails. "
                         "Give the talk-only time, excluding Q&A")
    ap.add_argument("--qa", type=float, default=0, metavar="MIN",
                    help="Q&A minutes, if included within --limit")
    ap.add_argument("--spoken", default=None, metavar="OUT",
                    help="writes a separate script for the audience panel (only what's spoken "
                         "aloud): no cues, time, backup slides, or questions")
    a = ap.parse_args(argv)
    if a.spoken:
        with io.open(a.spoken, "w", encoding="utf-8") as f:
            f.write(spoken_text(a.spec))
        print("=> %s  (for the panel, only what's spoken aloud)" % a.spoken)
    total, n, th = build(a.spec, a.out, a.thumbs, a.wpm)
    print("=> %s  (%d slide(s) · %s%s)"
          % (a.out, n, timing.hhmm(total), " · %d thumbnail(s)" % len(th) if th else ""))

    # Running over time is the most common accident in a talk, yet nothing has failed on
    # this so far. Printing the calculation alone does not get it read; giving it a limit
    # turns it into a gate.
    bad = 0
    # Does not report what it could not count as "short." A Korean script once got counted
    # as 0 words across the board, so a 10-minute talk showed `calculated 1:25`. Even with a
    # gate in place, this could not be caught structurally: 0 meant "could not count," not "short."
    _, slides, _ = load(a.spec)
    mute = timing.uncountable([x for s in slides for x in (s.get("say") or [])])
    if mute:
        print("   %d line(s) are written in characters this tool can't read." % len(mute))
        for x in mute[:3]:
            print("       %s" % x)
        print("     The time below comes out short by that much. Don't trust it:")
        print("     time it with a stopwatch, and fix timing.SYL_PER_SEC if needed.")
        bad = 1
    if a.limit:
        budget = (a.limit - a.qa) * 60.0
        # Compares after rounding to whole seconds. The display (`hhmm`) truncates the
        # seconds, so without rounding first, a fractional total like 720.4 seconds could
        # print as "calculated 12:00" and still fail as "0:00 over".
        total = float(int(total + 0.5))
        over = total - budget
        print("   limit %s%s · calculated %s · %s"
              % (timing.hhmm(budget),
                 " (excludes %g min of Q&A)" % a.qa if a.qa else "",
                 timing.hhmm(total),
                 "%s to spare" % timing.hhmm(-over) if over <= 0
                 else "%s over" % timing.hhmm(over)))
        if over > 0:
            print("   It needs to be cut. Dropping a slide beats talking faster:")
            print("     that's %.0fs per slide. Look at the longest slide first." % (total / max(1, n)))
            bad = 1
        elif over > -0.1 * budget:
            # `%%` only collapses to a single `%` inside a format string. This line has no
            # `%` formatting, so writing `10%%` here would print literally as written.
            print("   Less than 10% to spare. In the room it always runs slower than the calculation.")
    print("   This number is a calculation. Confirm it by reading it aloud once with a stopwatch.")
    return bad


if __name__ == "__main__":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8")
    sys.exit(main())
